/**
 * QCNOTE.js — TypeScript Code Generator
 * Compiles QCNOTE AST → TypeScript source that uses the QCNOTE runtime
 *
 * Emitted code pattern:
 *   const db = await QCRuntime.open("mydb");
 *   const result = await db.find("users", { where: ..., limit: ..., sort: ... });
 */

import type {
  QCNode,
  StoreDef,
  PutStmt,
  GetStmt,
  FindStmt,
  DelStmt,
  ClearStmt,
  CountStmt,
  ExportStmt,
  RawTSStmt,
  WhereExpr,
  QCValue,
  FieldDef,
  FieldType,
} from './qcnote-parser';

// ─── Code Generator ──────────────────────────────────────────────────────────

export interface CompilerOptions {
  dbName?: string; // IndexedDB database name, default "qcnote_db"
  dbVersion?: number; // IDB version
  secretKey?: string; // AES-256 key reference (variable name in TS)
  emitImports?: boolean; // Emit import statements at top
  emitTypes?: boolean; // Emit TypeScript interfaces for stores
  indent?: string;
}

const DEFAULT_OPTS: Required<CompilerOptions> = {
  dbName: 'qcnote_db',
  dbVersion: 1,
  secretKey: 'QCNOTE_SECRET',
  emitImports: true,
  emitTypes: true,
  indent: '  ',
};

export class QCCompiler {
  private opts: Required<CompilerOptions>;
  private stores: Map<string, StoreDef> = new Map();
  private lines: string[] = [];
  private ind = 0;

  constructor(opts: CompilerOptions = {}) {
    this.opts = { ...DEFAULT_OPTS, ...opts };
  }

  compile(nodes: QCNode[]): string {
    // First pass: collect store definitions
    for (const node of nodes) {
      if (node.kind === 'StoreDef') this.stores.set(node.name, node);
    }

    // Emit header
    if (this.opts.emitImports) {
      this.emit(`// Generated by QCNOTE.js — Do not edit manually`);
      this.emit(`// Fast · Light · Secure`);
      this.emit(`import { QCRuntime, QCDb, QCWhere } from "./qcnote-runtime";`);
      this.emit(``);
    }

    // Emit TypeScript interfaces for stores
    if (this.opts.emitTypes) {
      for (const store of this.stores.values()) {
        this.emitStoreInterface(store);
      }
    }

    // Emit schema registration
    this.emitSchemaBlock(Array.from(this.stores.values()));

    // Emit db open
    this.emit(
      `const _db = await QCRuntime.open(${JSON.stringify(this.opts.dbName)}, _schema, ${this.opts.dbVersion});`,
    );
    this.emit(``);

    // Second pass: emit DML statements
    for (const node of nodes) {
      this.compileNode(node);
    }

    return this.lines.join('\n');
  }

  // ── Schema Block ─────────────────────────────────────────────────────────

  private emitSchemaBlock(stores: StoreDef[]) {
    this.emit(`const _schema: QCStoreSchema[] = [`);
    this.ind++;
    for (const s of stores) {
      this.emit(`{`);
      this.ind++;
      this.emit(`name: ${JSON.stringify(s.name)},`);
      this.emit(`keyField: ${JSON.stringify(s.keyField)},`);
      this.emit(`keyAuto: ${s.keyAuto},`);
      if (s.ttl) this.emit(`ttl: ${JSON.stringify(s.ttl)},`);
      this.emit(`fields: [`);
      this.ind++;
      for (const f of s.fields) {
        this.emit(
          `{ name: ${JSON.stringify(f.name)}, type: ${JSON.stringify(f.type)}, indexed: ${f.indexed}, secret: ${f.secret} },`,
        );
      }
      this.ind--;
      this.emit(`],`);
      this.ind--;
      this.emit(`},`);
    }
    this.ind--;
    this.emit(`];`);
    this.emit(``);
  }

  // ── TypeScript Interface ──────────────────────────────────────────────────

  private emitStoreInterface(store: StoreDef) {
    const tsType: Record<FieldType, string> = {
      str: 'string',
      num: 'number',
      bool: 'boolean',
      json: 'Record<string, unknown>',
      bin: 'Uint8Array',
      date: 'Date',
    };

    this.emit(`export interface ${this.capitalize(store.name)}Record {`);
    this.ind++;
    this.emit(`${store.keyField}${store.keyAuto ? '?: ' : ': '}number;`);
    for (const f of store.fields) {
      const ty = tsType[f.type];
      const encrypted = f.secret ? ' // @secret — AES-256 encrypted' : '';
      const idx = f.indexed ? ' // @index' : '';
      this.emit(`${f.name}: ${ty};${encrypted}${idx}`);
    }
    if (store.ttl) this.emit(`_expires?: number; // TTL ${store.ttl}`);
    this.ind--;
    this.emit(`}`);
    this.emit(``);
  }

  // ── Node Compiler ─────────────────────────────────────────────────────────

  private compileNode(node: QCNode) {
    switch (node.kind) {
      case 'StoreDef':
        break; // Already handled
      case 'PutStmt':
        this.compilePut(node);
        break;
      case 'GetStmt':
        this.compileGet(node);
        break;
      case 'FindStmt':
        this.compileFind(node);
        break;
      case 'DelStmt':
        this.compileDel(node);
        break;
      case 'ClearStmt':
        this.compileClear(node);
        break;
      case 'CountStmt':
        this.compileCount(node);
        break;
      case 'ExportStmt':
        this.compileExport(node);
        break;
      case 'RawTSStmt':
        this.compileRawTS(node);
        break;
    }
  }

  private compilePut(node: PutStmt) {
    const store = this.stores.get(node.store);
    const rec = JSON.stringify(node.record, null, 2)
      .split('\n')
      .join('\n' + this.opts.indent.repeat(this.ind));
    const typeHint = store ? `<${this.capitalize(node.store)}Record>` : '';
    this.emit(`await _db.put${typeHint}(${JSON.stringify(node.store)}, ${rec});`);
  }

  private compileGet(node: GetStmt) {
    const store = this.stores.get(node.store);
    const typeHint = store ? `<${this.capitalize(node.store)}Record>` : '';

    if (node.byKey !== undefined) {
      this.emit(
        `const ${this.genVar(node.store)} = await _db.getById${typeHint}(${JSON.stringify(node.store)}, ${JSON.stringify(node.byKey)});`,
      );
      return;
    }

    const opts = this.buildQueryOpts(node);
    this.emit(
      `const ${this.genVar(node.store)} = await _db.get${typeHint}(${JSON.stringify(node.store)}, ${opts});`,
    );
  }

  private compileFind(node: FindStmt) {
    const store = this.stores.get(node.store);
    const typeHint = store ? `<${this.capitalize(node.store)}Record>` : '';
    const opts = this.buildQueryOpts(node);
    this.emit(
      `const ${this.genVar(node.store)} = await _db.find${typeHint}(${JSON.stringify(node.store)}, ${opts});`,
    );
  }

  private compileDel(node: DelStmt) {
    if (node.byKey !== undefined) {
      this.emit(
        `await _db.deleteById(${JSON.stringify(node.store)}, ${JSON.stringify(node.byKey)});`,
      );
      return;
    }
    const where = node.where ? this.compileWhere(node.where) : '{}';
    this.emit(`await _db.delete(${JSON.stringify(node.store)}, { where: ${where} });`);
  }

  private compileClear(node: ClearStmt) {
    this.emit(`await _db.clear(${JSON.stringify(node.store)});`);
  }

  private compileCount(node: CountStmt) {
    const where = node.where ? this.compileWhere(node.where) : '{}';
    this.emit(
      `const ${this.genVar(node.store, 'count')} = await _db.count(${JSON.stringify(node.store)}, { where: ${where} });`,
    );
  }

  private compileExport(node: ExportStmt) {
    const store = this.stores.get(node.store);
    if (!store) {
      this.emit(`// export: store "${node.store}" not defined — skipped`);
      return;
    }
    // Already emitted as interface, just create a type alias
    this.emit(`export type ${node.alias} = ${this.capitalize(node.store)}Record;`);
  }

  private compileRawTS(node: RawTSStmt) {
    this.emit(node.code);
  }

  // ── Query Options builder ─────────────────────────────────────────────────

  private buildQueryOpts(node: GetStmt | FindStmt): string {
    const parts: string[] = [];
    if (node.where) parts.push(`where: ${this.compileWhere(node.where)}`);
    if (node.limit !== undefined) parts.push(`limit: ${node.limit}`);
    if (node.sort)
      parts.push(
        `sort: { field: ${JSON.stringify(node.sort.field)}, dir: ${JSON.stringify(node.sort.dir)} }`,
      );
    return parts.length ? `{ ${parts.join(', ')} }` : '{}';
  }

  // ── WHERE Expression compiler ─────────────────────────────────────────────

  private compileWhere(expr: WhereExpr): string {
    switch (expr.kind) {
      case 'Condition': {
        const { field, op, value } = expr;
        if (op === 'between' && Array.isArray(value)) {
          return `{ field: ${JSON.stringify(field)}, op: "between", value: [${JSON.stringify(value[0])}, ${JSON.stringify(value[1])}] }`;
        }
        return `{ field: ${JSON.stringify(field)}, op: ${JSON.stringify(op)}, value: ${JSON.stringify(value)} }`;
      }
      case 'LogicExpr':
        return `{ ${expr.op}: [${this.compileWhere(expr.left)}, ${this.compileWhere(expr.right)}] }`;
      case 'NotExpr':
        return `{ not: ${this.compileWhere(expr.expr)} }`;
    }
  }

  // ── Helpers ───────────────────────────────────────────────────────────────

  private _varCounters: Record<string, number> = {};
  private genVar(base: string, suffix = 'result'): string {
    const key = base + suffix;
    const n = (this._varCounters[key] = (this._varCounters[key] ?? 0) + 1);
    return n === 1 ? `${base}_${suffix}` : `${base}_${suffix}${n}`;
  }

  private capitalize(s: string): string {
    return s.charAt(0).toUpperCase() + s.slice(1);
  }

  private emit(line: string) {
    this.lines.push(this.opts.indent.repeat(this.ind) + line);
  }
}

// ── Public API ─────────────────────────────────────────────────────────────

export function compileQCNOTE(nodes: QCNode[], opts?: CompilerOptions): string {
  return new QCCompiler(opts).compile(nodes);
}
